import Head from "next/head";
import { useContext } from "react";
import SingleComicPage from "../../src/components/SingleComicPage";
import { Context } from "../../src/Context";
import Loading from "../../src/components/Loading";

const ComicPage = ({ id }) => {
    const { comicsData } = useContext(Context);

    let comicToShow = null;

    if (comicsData) {
        comicsData.comics.map(item => {
            if (item.id === Number(id)) comicToShow = item;
        });

        return (
            <>
                <Head>
                    <title>Marvel Comics Shop</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <SingleComicPage comic={comicToShow} />
            </>
        );
    };

    return (
        <>
            <Head>
                <title>Marvel Comics Shop</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Loading />
        </>
    );
};

export function getServerSideProps(context) {
    return {
        props: {
            id: context.query.id,
        }
    }
};

export default ComicPage;