import Head from "next/head";
import { useContext } from "react";
import { Context } from "../../src/Context";
import { ItemAddedMain, ItemContainer, ButtonsContainer } from "../../src/styles/itemadded";
import { BsCheckCircleFill } from 'react-icons/bs';
import Link from "next/link";
import Image from "next/image";

const ItemAdded = ({ id }) => {
    const { cartItems } = useContext(Context);

    let comicAdded = null;

    if (cartItems[0]) {
        cartItems.map(item => {
            if (item.id === Number(id)) comicAdded = item;
        });
    }

    return (
        <>
            <Head>
                <title>Marvel Comics Shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/spiderman.ico" />
            </Head>
            <ItemAddedMain>
                <section>
                    {
                        (comicAdded) ? (
                            <>
                                <h1><strong><BsCheckCircleFill /></strong> Item adicionado ao carrinho.</h1>
                                <ItemContainer>
                                    <Image src={`${comicAdded.thumbnail.path}.${comicAdded.thumbnail.extension}`} height={150} width={100}/>
                                    <span>{comicAdded.title}</span>
                                </ItemContainer>
                                <ButtonsContainer>
                                    <Link href="/">
                                        <button>Continuar comprando</button>
                                    </Link>
                                    <Link href="/cart">
                                        <button>Ir para o carrinho</button>
                                    </Link>
                                </ButtonsContainer>
                            </>
                        ) : (
                            <>
                                <h1>Nenhuma HQ foi adicionada ao carrinho.</h1>
                                <ButtonsContainer>
                                    <Link href="/">
                                        <button>Continuar comprando</button>
                                    </Link>
                                    <Link href="/cart">
                                        <button>Ir para o carrinho</button>
                                    </Link>
                                </ButtonsContainer>
                            </>
                        )
                    }
                </section>
            </ItemAddedMain>
        </>
    );
};

export function getServerSideProps(context) {
    return {
        props: {
            id: context.query.id,
        }
    }
};

export default ItemAdded;