import Head from 'next/head';
import { Context } from "../../src/Context";
import { useContext, useEffect, useState } from "react";
import { CartMain, CartSection, PaymentSection, CouponSection, InputField, InputButton, EmptyCartElement, PurchaseMadeContainer, ButtonsContainer } from "../../src/styles/cart";
import CartItem from "../../src/components/CartItem";
import { BsCheckCircleFill } from 'react-icons/bs';
import { GiSpiderMask } from 'react-icons/gi';
import Link from "next/link";
import { validateCoupon } from "../../src/helpers/coupons";

const Cart = () => {
    const { cartItems, setCartItems, usedCoupons, setUsedCoupons, couponInformation, setCouponInformation, orders, setOrders } = useContext(Context);
    const [totalPrice, setTotalPrice] = useState(0);
    const [cartUpdated, setCartUpdated] = useState(false);
    const [purchaseMade, setPurchaseMade] = useState(false);
    const [coupon, setCoupon] = useState('');
    let renderedItems = [];

    useEffect(() => {
        setCartUpdated(false);
        setTotalPrice(cartItems.reduce((soma, item) => soma + item.prices[0].price, 0));
        setCouponInformation(validateCoupon(cartItems, usedCoupons));
    }, [cartItems, cartUpdated]);

    const handleSubmit = (e) => {
        e.preventDefault();
        setUsedCoupons(prevUsedCoupons => [...prevUsedCoupons, coupon]);
        setCoupon('');
        setCartUpdated(true);
    };

    return (
        <>
            <Head>
                <title>Marvel Comics Shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/spiderman.ico" />
            </Head>
            <CartMain>
                {
                    purchaseMade ? (
                        <PurchaseMadeContainer>
                            <h2><strong><BsCheckCircleFill /></strong> Seu pedido foi feito.</h2>
                            <h2>Obrigado por comprar conosco <span><GiSpiderMask /></span></h2>
                            <ButtonsContainer>
                                <Link href="/">
                                    <button>Comprar novamente</button>
                                </Link>
                                <Link href="/user">
                                    <button>Meus pedidos</button>
                                </Link>
                            </ButtonsContainer>
                        </PurchaseMadeContainer>
                    ) : (
                        <>
                            <CartSection>
                                <table>
                                    <tbody>
                                        {
                                            Boolean(cartItems[0]) ? (
                                                cartItems.map(item => {
                                                    if (!renderedItems.includes(item)) {
                                                        renderedItems = [...renderedItems, item];
                                                        return <CartItem key={item.id} comic={item} setCartUpdated={setCartUpdated} />;
                                                    };
                                                })) : (
                                                <tr>
                                                    <EmptyCartElement>
                                                        <h3>Carrinho vazio.</h3>
                                                        <Link href="/"><button>Página inicial</button></Link></EmptyCartElement>
                                                </tr>
                                            )
                                        }
                                    </tbody>
                                </table>
                            </CartSection>
                            <PaymentSection>
                                <p><strong>Preço total:</strong> ${totalPrice ? totalPrice.toFixed(2) : '0.00'}</p>
                                <p><strong>Desconto:</strong> ${couponInformation ? couponInformation.discount.toFixed(2) : '0.00'}</p>
                                <hr />
                                <p><strong>Preço final: </strong> ${couponInformation ? (totalPrice - couponInformation.discount).toFixed(2) : totalPrice.toFixed(2)}</p>
                                <button onClick={() => {
                                    if (cartItems[0]) {
                                        setOrders([...orders, {
                                            cartItems: cartItems,
                                            totalOrderPrice: couponInformation ? (totalPrice - couponInformation.discount) : totalPrice,
                                        }]);
                                        setCartItems([]);
                                        setUsedCoupons([]);
                                        setPurchaseMade(true);
                                    }
                                }}>Finalizar compra</button>
                            </PaymentSection>
                            <CouponSection>
                                <form onSubmit={handleSubmit}>
                                    <InputField type="text" placeholder="CUPOM DE DESCONTO" value={coupon} onChange={e => setCoupon(e.target.value)} />
                                    <InputButton type="submit" value="Aplicar" />
                                </form>
                                <br />
                                {
                                    (couponInformation && couponInformation.availableCouponsUsed[0]) ? (
                                        <span>Cupons válidos utilizados:
                                            {
                                                couponInformation.availableCouponsUsed.map(item => <strong>| {item} |</strong>)
                                            }
                                        </span>
                                    ) : (
                                        <span>Nenhum cupom válido foi utilizado ainda.</span>
                                    )
                                }
                            </CouponSection>
                        </>
                    )
                }
            </CartMain>
        </>
    );
};

export default Cart;

