import Head from 'next/head';
import React, { useState, useContext, useEffect } from "react";
import Comic from "../src/components/Comic";
import Pagination from "../src/components/Pagination";
import { HomeMain, HomeSection, InputField, InputButton } from "../src/styles/homepage";
import { Context } from "../src/Context";
import Loading from "../src/components/Loading";
import { ITEMS_PER_PAGE, TOTAL_ITEMS } from "./_app";

const Home = () => {
  const { comicsData } = useContext(Context);
  const [comicsToShow, setComicsToShow] = useState()
  const [hqFilter, setHqfilter] = useState('');
  const [offset, setOffset] = useState(0);
  
  useEffect(() => {
    if(comicsData) {
      setComicsToShow(comicsData.comics.slice(offset, offset + ITEMS_PER_PAGE));
    };
  }, [comicsData])
  
  const handleSubmit = (e) => {
    e.preventDefault();
    setHqfilter('');
  };

  const handleChange = (e) => {
    e.preventDefault()
    setHqfilter(e.target.value);
    setComicsToShow(comicsData.comics.filter(item => item.title.toLowerCase().includes(hqFilter.toLowerCase())).slice(offset, offset + ITEMS_PER_PAGE));
    console.log('comicsToShow', comicsToShow);
  };

  return comicsToShow ? (
    <>
      <Head>
        <title>Marvel Comics</title>
        <meta name="Marvel Comics Shop" content="Generated by create next app" />
        <link rel="icon" href="/spiderman.ico" />
      </Head>
      <HomeMain>
        <HomeSection>
          <form onSubmit={handleSubmit}>
            <InputField type="text" placeholder="Busque por uma HQ" value={hqFilter} onChange={handleChange}/>
            <InputButton type="submit" value="Buscar"/>
          </form>
          {
            comicsToShow.map(item => <Comic comic={item} />)
          }
          {
            comicsToShow.length > 0 ? (
            <Pagination limit={ITEMS_PER_PAGE} total={comicsToShow.length} offset={offset} setOffset={setOffset} />
            ) : null
          }
        </HomeSection>
      </HomeMain>
    </>
  ) : <Loading />;
};

export default Home;