import Head from "next/head";
import OrdersSection from "../src/components/OrdersSection";
import { UserMain } from "../src/styles/userpage";

const UserPage = () => {
    return (
        <>
            <Head>
                <title>Marvel Comics Shop</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <UserMain>
                <OrdersSection />
            </UserMain>
        </>
    );
};

export default UserPage;